DROP TABLE CINEMA_HALLS;
DROP TABLE CINEMAS;
DROP TABLE COUNTRIES;
DROP TABLE EMPLOYEES;
DROP TABLE JOBS;
DROP TABLE LOCATIONS;
DROP TABLE MOVIES;
DROP TABLE SEATS;
DROP TABLE SHOWTIMES;
DROP TABLE SHOWTIMES_ARCHIVE;
DROP TABLE USERS;
DROP TABLE BOOKINGS;

--DELETE FROM CINEMA_HALLS2;
--DELETE FROM CINEMAS2;
--DELETE FROM COUNTRIES2;
--DELETE FROM EMPLOYEES2;
--DELETE FROM JOBS2;
--DELETE FROM LOCATIONS2;
--DELETE FROM MOVIES2;
--DELETE FROM SEATS2;
--DELETE FROM SHOWTIMES2;
--DELETE FROM USERS2;
--DELETE FROM BOOKINGS2;
--
--DROP TABLE USERS2;
--DROP TABLE BOOKINGS2;
--DROP TABLE CINEMA_HALLS2;
--DROP TABLE SHOWTIMES2_ARCHIVE;
--DROP TABLE CINEMAS2;
--DROP TABLE COUNTRIES2;
--DROP TABLE EMPLOYEES2;
--DROP TABLE JOBS2;
--DROP TABLE LOCATIONS2;
--DROP TABLE MOVIES2;
--DROP TABLE SEATS2;
--DROP TABLE SHOWTIMES2;

