set serveroutput on;

-- Creating Tables
CREATE TABLE COUNTRIES(
    country_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_name VARCHAR2(50),
    PRIMARY KEY (country_id)
);

CREATE TABLE LOCATIONS(
    location_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city VARCHAR2(50),
    postal_code VARCHAR2(20),
    state_province VARCHAR2(50),
    country_id NUMBER(6),
    PRIMARY KEY (location_id)
);

CREATE TABLE CINEMAS(
    cinema_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cinema_name VARCHAR2(100),
    street_address VARCHAR2(50),
    phone_number VARCHAR2(20),
    email VARCHAR2(50),
    location_id NUMBER(6),
    PRIMARY KEY (cinema_id)
);

CREATE TABLE EMPLOYEES(
    employee_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(50),
    phone_number VARCHAR2(20),
    job_id NUMBER(6),
    cinema_id NUMBER(6),
    hire_date DATE,
    salary FLOAT,
    contract_type VARCHAR2(50),
    contract_end DATE,
    PRIMARY KEY (employee_id)
);

CREATE TABLE JOBS(
    job_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_name VARCHAR2(100),
    min_salary FLOAT,
    max_salary FLOAT,
    PRIMARY KEY (job_id)
);

CREATE TABLE CINEMA_HALLS(
    cinema_hall_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hall_name VARCHAR2(50),
    hall_number NUMBER(6),
    cinema_id NUMBER(6),
    PRIMARY KEY (cinema_hall_id)
);


CREATE TABLE SEATS(
    seat_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cinema_hall_id NUMBER(6),
    seat_number NUMBER(6),
    seat_type VARCHAR2(50),
    status VARCHAR2(50),
    PRIMARY KEY (seat_id)
);

CREATE TABLE SHOWTIMES(
    showtime_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    showtime_name VARCHAR2(255),
    movie_id NUMBER(6),
    cinema_hall_id NUMBER(6),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    ticket_price FLOAT,
    PRIMARY KEY (showtime_id)
);
CREATE TABLE SHOWTIMES_ARCHIVE(
    showtime_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    showtime_name VARCHAR2(255),
    movie_id NUMBER(6),
    cinema_hall_id NUMBER(6),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    ticket_price FLOAT,
    archive_timestamp TIMESTAMP,
    PRIMARY KEY (showtime_id)
);
CREATE TABLE MOVIES(
    movie_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_name VARCHAR2(255),
    movie_length NUMBER(6),
    movie_poster VARCHAR2(255),
    movie_language VARCHAR2(50),
    release_date TIMESTAMP,
    movie_description VARCHAR2(255),
    genre VARCHAR2(100),
    PRIMARY KEY (movie_id)
);

CREATE TABLE BOOKINGS(
    booking_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    showtime_id NUMBER(6),
    user_id NUMBER(6),
    seat_id NUMBER(6),
    payment_status VARCHAR2(50),
    purchase_date TIMESTAMP,
    PRIMARY KEY (booking_id)
);

CREATE TABLE USERS(
    user_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR2(100),
    email VARCHAR2(150),
    phone_number VARCHAR2(50),
    PRIMARY KEY (user_id)
);

// COUNTRY - LOCATIONS
ALTER TABLE LOCATIONS 
ADD CONSTRAINT fk_countries__locations_country_id
FOREIGN KEY (country_id) 
REFERENCES COUNTRIES(country_id)
ON DELETE CASCADE;

// LOCATIONS - CINEMAS
ALTER TABLE CINEMAS 
ADD CONSTRAINT fk_locations__cinemas_location_id
FOREIGN KEY (location_id) 
REFERENCES LOCATIONS(location_id)
ON DELETE CASCADE;

// CINEMAS - EMPLOYEES
ALTER TABLE EMPLOYEES
ADD CONSTRAINT fk_cinemas__employees_cinema_id
FOREIGN KEY (cinema_id) 
REFERENCES CINEMAS(cinema_id)
ON DELETE CASCADE;

// JOBS - EMPLOYEES
ALTER TABLE EMPLOYEES
ADD CONSTRAINT fk_jobs__employees_job_id
FOREIGN KEY (job_id) 
REFERENCES JOBS(job_id)
ON DELETE CASCADE;

// CINEMAS - CINEMA_HALLS
ALTER TABLE CINEMA_HALLS
ADD CONSTRAINT fk_cinemas__cinema_hall_cinema_id
FOREIGN KEY (cinema_id) 
REFERENCES CINEMAS(cinema_id)
ON DELETE CASCADE;

// CINEMA_HALLS - SEATS
ALTER TABLE SEATS
ADD CONSTRAINT fk_cinema_halls__seats__cinema_hall_id
FOREIGN KEY (cinema_hall_id) 
REFERENCES CINEMA_HALLS(cinema_hall_id)
ON DELETE CASCADE;

// CINEMA_HALLS - SHOWTIMES
ALTER TABLE SHOWTIMES
ADD CONSTRAINT fk_cinema_halls__showtimes__cinema_hall_id
FOREIGN KEY (cinema_hall_id) 
REFERENCES CINEMA_HALLS(cinema_hall_id)
ON DELETE CASCADE;

ALTER TABLE SHOWTIMES_ARCHIVE
ADD CONSTRAINT fk_cinema_halls__showtimes_archive__cinema_hall_id
FOREIGN KEY (cinema_hall_id) 
REFERENCES CINEMA_HALLS(cinema_hall_id)
ON DELETE CASCADE;

// MOVIES - SHOWTIMES
ALTER TABLE SHOWTIMES
ADD CONSTRAINT fk_movies__showtimes__movie_id
FOREIGN KEY (movie_id) 
REFERENCES MOVIES(movie_id)
ON DELETE CASCADE;

ALTER TABLE SHOWTIMES_ARCHIVE
ADD CONSTRAINT fk_movies__showtimes_archive_movie_id
FOREIGN KEY (movie_id) 
REFERENCES MOVIES(movie_id)
ON DELETE CASCADE;

// SHOWTIMES - BOOKINGS
ALTER TABLE BOOKINGS
ADD CONSTRAINT fk_showtimes__bookings__showtime_id
FOREIGN KEY (showtime_id) 
REFERENCES SHOWTIMES(showtime_id)
ON DELETE CASCADE;

// USERS - BOOKINGS
ALTER TABLE BOOKINGS
ADD CONSTRAINT fk_users__bookings__user_id
FOREIGN KEY (user_id) 
REFERENCES USERS(user_id)
ON DELETE CASCADE;

--// DROP CONSTRAINTS
--ALTER TABLE LOCATIONS DROP CONSTRAINT fk_countries__locations_country_id;
--ALTER TABLE CINEMAS DROP CONSTRAINT fk_locations__cinemas_location_id;
--ALTER TABLE EMPLOYEES DROP CONSTRAINT fk_cinemas__employees_cinema_id;
--ALTER TABLE EMPLOYEES DROP CONSTRAINT fk_jobs__employees_job_id;
--ALTER TABLE CINEMA_HALLS DROP CONSTRAINT fk_cinemas__cinema_hall_cinema_id;
--ALTER TABLE SEATS DROP CONSTRAINT fk_cinema_halls__seats__cinema_hall_id;
--ALTER TABLE SHOWTIMES DROP CONSTRAINT fk_cinema_halls__showtimes__cinema_hall_id;
--ALTER TABLE SHOWTIMES DROP CONSTRAINT fk_movies__showtimes__movie_id;
--ALTER TABLE BOOKINGS DROP CONSTRAINT fk_showtimes__bookings__showtime_id;
--ALTER TABLE BOOKINGS DROP CONSTRAINT fk_users__bookings__user_id;


--
--CREATE TABLE COUNTRIES2(
--    country_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    country_name VARCHAR2(50),
--    PRIMARY KEY (country_id)
--);
--
--CREATE TABLE LOCATIONS2(
--    location_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    city VARCHAR2(50),
--    postal_code VARCHAR2(20),
--    state_province VARCHAR2(50),
--    country_id NUMBER(6),
--    PRIMARY KEY (location_id)
--);
--
--CREATE TABLE CINEMAS2(
--    cinema_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    cinema_name VARCHAR2(100),
--    street_address VARCHAR2(50),
--    phone_number VARCHAR2(20),
--    email VARCHAR2(50),
--    location_id NUMBER(6),
--    PRIMARY KEY (cinema_id)
--);
--
--CREATE TABLE EMPLOYEES2(
--    employee_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    first_name VARCHAR2(50),
--    last_name VARCHAR2(50),
--    email VARCHAR2(50),
--    phone_number VARCHAR2(20),
--    job_id NUMBER(6),
--    cinema_id NUMBER(6),
--    hire_date DATE,
--    salary FLOAT,
--    contract_type VARCHAR2(50),
--    contract_end DATE,
--    PRIMARY KEY (employee_id)
--);
--
--CREATE TABLE JOBS2(
--    job_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    job_name VARCHAR2(100),
--    min_salary FLOAT,
--    max_salary FLOAT,
--    PRIMARY KEY (job_id)
--);
--
--CREATE TABLE CINEMA_HALLS2(
--    cinema_hall_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    hall_name VARCHAR2(50),
--    hall_number NUMBER(6),
--    cinema_id NUMBER(6),
--    PRIMARY KEY (cinema_hall_id)
--);
--
--
--CREATE TABLE SEATS2(
--    seat_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    cinema_hall_id NUMBER(6),
--    seat_number NUMBER(6),
--    seat_type VARCHAR2(50),
--    status VARCHAR2(50),
--    PRIMARY KEY (seat_id)
--);
--
--CREATE TABLE SHOWTIMES2(
--    showtime_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    showtime_name VARCHAR2(255),
--    movie_id NUMBER(6),
--    cinema_hall_id NUMBER(6),
--    start_time TIMESTAMP,
--    end_time TIMESTAMP,
--    ticket_price FLOAT,
--    PRIMARY KEY (showtime_id)
--);
--
--CREATE TABLE SHOWTIMES2_ARCHIVE(
--    showtime_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    showtime_name VARCHAR2(255),
--    movie_id NUMBER(6),
--    cinema_hall_id NUMBER(6),
--    start_time TIMESTAMP,
--    end_time TIMESTAMP,
--    ticket_price FLOAT,
--    archive_timestamp TIMESTAMP,
--    PRIMARY KEY (showtime_id)
--);
--
--CREATE TABLE MOVIES2(
--    movie_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    movie_name VARCHAR2(255),
--    movie_length NUMBER(6),
--    movie_poster VARCHAR2(255),
--    movie_language VARCHAR2(50),
--    release_date TIMESTAMP,
--    movie_description VARCHAR2(255),
--    genre VARCHAR2(100),
--    PRIMARY KEY (movie_id)
--);
--
--CREATE TABLE BOOKINGS2(
--    booking_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    showtime_id NUMBER(6),
--    user_id NUMBER(6),
--    seat_id NUMBER(6),
--    payment_status VARCHAR2(50),
--    purchase_date TIMESTAMP,
--    PRIMARY KEY (booking_id)
--);
--
--CREATE TABLE USERS2(
--    user_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    user_name VARCHAR2(100),
--    email VARCHAR2(150),
--    phone_number VARCHAR2(50),
--    PRIMARY KEY (user_id)
--);
--
--// COUNTRY - LOCATIONS
--ALTER TABLE LOCATIONS2 
--ADD CONSTRAINT fk_countries__locations_country_id2
--FOREIGN KEY (country_id) 
--REFERENCES COUNTRIES2(country_id)
--ON DELETE CASCADE;
--
--// LOCATIONS - CINEMAS
--ALTER TABLE CINEMAS2 
--ADD CONSTRAINT fk_locations__cinemas_location_id2
--FOREIGN KEY (location_id) 
--REFERENCES LOCATIONS2(location_id)
--ON DELETE CASCADE;
--
--// CINEMAS - EMPLOYEES
--ALTER TABLE EMPLOYEES2
--ADD CONSTRAINT fk_cinemas__employees_cinema_id2
--FOREIGN KEY (cinema_id) 
--REFERENCES CINEMAS2(cinema_id)
--ON DELETE CASCADE;
--
--// JOBS - EMPLOYEES
--ALTER TABLE EMPLOYEES2
--ADD CONSTRAINT fk_jobs__employees_job_id2
--FOREIGN KEY (job_id) 
--REFERENCES JOBS2(job_id)
--ON DELETE CASCADE;
--
--// CINEMAS - CINEMA_HALLS
--ALTER TABLE CINEMA_HALLS2
--ADD CONSTRAINT fk_cinemas__cinema_hall_cinema_id2
--FOREIGN KEY (cinema_id) 
--REFERENCES CINEMAS2(cinema_id)
--ON DELETE CASCADE;
--
--// CINEMA_HALLS - SEATS
--ALTER TABLE SEATS2
--ADD CONSTRAINT fk_cinema_halls__seats__cinema_hall_id2
--FOREIGN KEY (cinema_hall_id) 
--REFERENCES CINEMA_HALLS2(cinema_hall_id)
--ON DELETE CASCADE;
--
--// CINEMA_HALLS - SHOWTIMES
--ALTER TABLE SHOWTIMES2
--ADD CONSTRAINT fk_cinema_halls__showtimes__cinema_hall_id2
--FOREIGN KEY (cinema_hall_id) 
--REFERENCES CINEMA_HALLS2(cinema_hall_id)
--ON DELETE CASCADE;
--
--ALTER TABLE SHOWTIMES2_ARCHIVE
--ADD CONSTRAINT fk_cinema_halls__showtimes__cinema_hall_id2
--FOREIGN KEY (cinema_hall_id) 
--REFERENCES CINEMA_HALLS2(cinema_hall_id)
--ON DELETE CASCADE;
--
--// MOVIES - SHOWTIMES
--ALTER TABLE SHOWTIMES2
--ADD CONSTRAINT fk_movies__showtimes__movie_id2
--FOREIGN KEY (movie_id) 
--REFERENCES MOVIES2(movie_id)
--ON DELETE CASCADE;
--
--ALTER TABLE SHOWTIMES2_ARCHIVE
--ADD CONSTRAINT fk_movies__showtimes__movie_id2
--FOREIGN KEY (movie_id) 
--REFERENCES MOVIES2(movie_id)
--ON DELETE CASCADE;
--
--// SHOWTIMES - BOOKINGS
--ALTER TABLE BOOKINGS2
--ADD CONSTRAINT fk_showtimes__bookings__showtime_id2
--FOREIGN KEY (showtime_id) 
--REFERENCES SHOWTIMES2(showtime_id)
--ON DELETE CASCADE;
--
--// USERS - BOOKINGS
--ALTER TABLE BOOKINGS2
--ADD CONSTRAINT fk_users__bookings__user_id2
--FOREIGN KEY (user_id) 
--REFERENCES USERS2(user_id)
--ON DELETE CASCADE;

--// DROP CONSTRAINTS
--ALTER TABLE LOCATIONS DROP CONSTRAINT fk_countries__locations_country_id2;
--ALTER TABLE CINEMAS DROP CONSTRAINT fk_locations__cinemas_location_id2;
--ALTER TABLE EMPLOYEES DROP CONSTRAINT fk_cinemas__employees_cinema_id2;
--ALTER TABLE EMPLOYEES DROP CONSTRAINT fk_jobs__employees_job_id2;
--ALTER TABLE CINEMA_HALLS DROP CONSTRAINT fk_cinemas__cinema_hall_cinema_id2;
--ALTER TABLE SEATS DROP CONSTRAINT fk_cinema_halls__seats__cinema_hall_id2;
--ALTER TABLE SHOWTIMES DROP CONSTRAINT fk_cinema_halls__showtimes__cinema_hall_id2;
--ALTER TABLE SHOWTIMES DROP CONSTRAINT fk_movies__showtimes__movie_id2;
--ALTER TABLE BOOKINGS DROP CONSTRAINT fk_showtimes__bookings__showtime_id2;
--ALTER TABLE BOOKINGS DROP CONSTRAINT fk_users__bookings__user_id2;