-- Creating Tables
CREATE TABLE COUNTRIES(
    country_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_name VARCHAR2(50),
    PRIMARY KEY (country_id)
);

CREATE TABLE LOCATIONS(
    location_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city VARCHAR2(50),
    postal_code VARCHAR2(20),
    state_province VARCHAR2(50),
    country_id NUMBER(6),
    PRIMARY KEY (location_id)
);

CREATE TABLE CINEMAS(
    cinema_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cinema_name VARCHAR2(100),
    street_address VARCHAR2(50),
    phone_number VARCHAR2(20),
    email VARCHAR2(50),
    location_id NUMBER(6),
    PRIMARY KEY (cinema_id)
);

CREATE TABLE EMPLOYEES(
    employee_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(50),
    phone_number VARCHAR2(20),
    hire_date DATE,
    job_id NUMBER(6),
    salary FLOAT,
    cinema_id NUMBER(6),
    contract_type VARCHAR2(50),
    contract_end DATE,
    PRIMARY KEY (employee_id)
);

CREATE TABLE JOBS(
    job_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_name VARCHAR2(100),
    min_salary FLOAT,
    max_salary FLOAT,
    PRIMARY KEY (job_id)
);

CREATE TABLE CINEMA_HALLS(
    cinema_hall_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hall_name VARCHAR2(50),
    hall_number NUMBER(6),
    cinema_id NUMBER(6),
    PRIMARY KEY (cinema_hall_id)
);


CREATE TABLE SEATS(
    seat_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cinema_hall_id NUMBER(6),
    seat_number NUMBER(6),
    seat_type VARCHAR2(50),
    status VARCHAR2(50),
    PRIMARY KEY (seat_id)
);

CREATE TABLE SHOWTIMES(
    showtime_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    showtime_name VARCHAR2(255),
    movie_id NUMBER(6),
    cinema_hall_id NUMBER(6),
    start_time DATE,
    end_time DATE,
    ticket_price FLOAT,
    PRIMARY KEY (showtime_id)
);

CREATE TABLE MOVIES(
    movie_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movie_length NUMBER(6),
    movie_poster VARCHAR2(255),
    movie_language VARCHAR2(50),
    release_date DATE,
    movie_description VARCHAR2(255),
    genre VARCHAR2(100),
    movie_type VARCHAR2(255),
    PRIMARY KEY (movie_id)
);

CREATE TABLE BOOKINGS(
    booking_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    showtime_id NUMBER(6),
    user_id NUMBER(6),
    seat_id NUMBER(6),
    payment_status VARCHAR2(50),
    purchase_date DATE,
    PRIMARY KEY (booking_id)
);

CREATE TABLE USERS(
    user_id NUMBER(6) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR2(100),
    email VARCHAR2(150),
    phone_number VARCHAR2(50),
    PRIMARY KEY (user_id)
);


