CREATE OR REPLACE TRIGGER trg_check_payment_status
BEFORE INSERT OR UPDATE ON BOOKINGS
FOR EACH ROW
BEGIN
  IF UPPER(:NEW.PAYMENT_STATUS) NOT IN ('PAID', 'NOT_PAID') THEN
    RAISE_APPLICATION_ERROR(-20001, 'Niedozwolony status płatności. Dozwolone wartości to: PAID, NOT_PAID.');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_set_status_update_timestamp
BEFORE UPDATE ON BOOKINGS
FOR EACH ROW
BEGIN
  IF UPPER(:OLD.PAYMENT_STATUS) = 'NOT_PAID'
     AND UPPER(:NEW.PAYMENT_STATUS) = 'PAID' THEN

    :NEW.PURCHASE_DATE := SYSTIMESTAMP;
  END IF;
END;
/

INSERT INTO BOOKINGS (BOOKING_ID, SHOWTIME_ID, USER_ID, SEAT_ID, PAYMENT_STATUS, PURCHASE_DATE) VALUES (10, 4, 4, 402, 'PAID', NULL)